### ISSUE TITLE
Update of schema-typed to 2.1.0

### ISSUE THREAD

**Issue by rfranchi** [rsuite/rsuite#3101] opened 2023-03-06 14:42 UTC
### What version of rsuite are you using?

5.0.0

### What version of React are you using?

17.0.2

### What browser are you using?

Chrome

### Describe the Bug

The rsuite package.json has the dependency of "schema-typed": "**^**2.0.1"

With the recent update of the version of this dependency for the 2.1.0, our project started to break the build:

ERROR in ./node_modules/schema-typed/es/ArrayType.js 59:66
Module parse failed: Unexpected token (59:66)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|                     return type.check(value, data, name);
|                 });
|  >               const hasError = !!checkResults.find(item => item?.hasError);
|                 return {
|                     hasError,
 @ ./node_modules/schema-typed/es/index.js 5:0-51 9:0-112
 @ ./node_modules/rsuite/esm/Schema/Schema.js
 @ ./node_modules/rsuite/esm/Schema/index.js
 @ ./node_modules/rsuite/esm/index.js
 @ ./node_modules/example-react/dist/components/headers/index.js
 @ ./node_modules/example-react/dist/components/index.js
 @ ./node_modules/example-react/dist/index.js
 @ ./src/apps-intra/list/list-form-intra-app.jsx

This dependency (and others shouldn't had the the specific version or tilde (~) version type?

Thank you in advance.

### Expected Behavior

Older versions don't break.

**Comment by SevenOutman** [comment] 2023-03-07 06:13
Hi @rfranchi , the log seems to indicate that your build system does not support optional chaining. If you are using Babel, try adding [babel-plugin-proposal-optional-chaining](https://babeljs.io/docs/babel-plugin-proposal-optional-chaining)

**Comment by simonguo** [comment] 2023-03-07 07:02
@SevenOutman  Our rsuite library relies on the [^version (Compatible with version)](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#dependencies) of schema-typed. If the project using it does not use `package-lock.json` or `yarn.lock`, the version of schema-typed in the project will be automatically installed as version 2.1.0 during installation.

This issue may be caused by a change in the compilation method of [schema-typed from Babel to ts-node](https://github.com/rsuite/schema-typed/pull/64) in version 2.1.0.

I think we need to fix the compatibility of schema-typed, and also consider changing the rsuite library's dependency on schema-typed to `~version` (Approximately equivalent to version).

**Comment by SevenOutman** [comment] 2023-03-08 07:07
> I think we need to fix the compatibility of schema-typed, and also consider changing the rsuite library's dependency on schema-typed to `~version` (Approximately equivalent to version).

Agreed that `schema-typed` build should be fixed. But changing dep version range from `^` to `~` may not help because patch updates can contain bugs like this one anyway.

**Comment by Sidneycarlinijr** [comment] 2023-03-08 13:32
I'm happy to hear that you are actively working on resolving the issue that's causing problems with community product's build in both development and production environments.

Could you please provide us with any new information or updates regarding this issue? Here we are eagerly waiting to receive any updates so we can build our new releases.

We appreciate your efforts to solve this issue.

Please let me know if i can help you guys.

**Comment by Sidneycarlinijr** [comment] 2023-03-08 14:45
> I'm happy to hear that you are actively working on resolving the issue that's causing problems with community product's build in both development and production environments.
> 
> Could you please provide us with any new information or updates regarding this issue? Here we are eagerly waiting to receive any updates so we can build our new releases.
> 
> We appreciate your efforts to solve this issue.
> 
> Please let me know if i can help you guys.

Problem solved. Thanks! ❤️ ❤️

**Comment by SevenOutman** [comment] 2023-05-09 02:17
I'm closing this issue as it seems to have been resolved. Feel free to re-open if it's actually not.

**Closed by SevenOutman** 2023-05-09 02:17 UTC
Labels: status: Needs More Info
