### ISSUE TITLE
Unable to preventDefault inside passive event listener for table on drag

### ISSUE THREAD

**Issue by youanswer** [rsuite/rsuite#447] opened 2019-04-17 02:11 UTC
For table component, drag events on mobile/tablet produce errors in Chrome:
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive.
### Bug, feature request, or proposal:
Bug

### What is the expected behavior?
No errors in the console on scroll on mobile

### What is the current behavior?
There are 

### What are the steps to reproduce?
Open dev console on chrome, toggle device toolbar, try to drag to scroll the table
http://recordit.co/wqbcUSvSlg

**Comment by simonguo** [comment] 2019-04-17 02:16
Fixed in version 3.8.0  https://github.com/rsuite/rsuite/releases/tag/3.8.0

https://github.com/rsuite/rsuite-table/pull/73

**Comment by simonguo** [comment] 2019-04-17 02:24
Sorry, I found that there is still a problem on the mobile side and we will fix it as soon as possible.

**Comment by youanswer** [comment] 2019-04-17 04:07
@simonguo I saw you've submitted the PR and bumped the rsuite-table version with the patch. I've used the 3.5.3 version, but the scrolling of table on mobile stopped working for me. Possible solution is removing `event.preventDefault()` for handleTouchMove as it fixes the scrolling. Can you take a look please?
Thank you!

**Comment by simonguo** [comment] 2019-04-17 05:59
The problem is that chrome ignores the call to preventDefault by default in order to improve the scrolling experience.

The fix is ​​to set `passive: true` when binding events. This issue will be prioritized and fixed in the next release.

**Comment by simonguo** [comment] 2019-04-18 01:54
@youanswer  Fixed in `rsuite@3.8.3`

**Closed** 2019-04-24 06:57 UTC
Labels: bug
