### ISSUE TITLE
Invalid after style modification

### ISSUE THREAD

**Issue by Tian-YJ** [rsuite/rsuite#3793] opened 2024-05-10 07:14 UTC
![26431715324659_ pic](https://github.com/rsuite/rsuite/assets/35914704/7ed2cb77-6fcb-42b3-8169-172511706947)
![26421715324658_ pic](https://github.com/rsuite/rsuite/assets/35914704/c94e1fab-8045-45c7-a6aa-7a11f325aa22)

beacuse i used your component,so i hope you can solve the problem

my requirement is the btn and border bg is #333,but Invalid after style modification

**Comment by simonguo** [comment] 2024-05-10 07:28
If you write CSS to override styles, but find that the styles are not taking effect, there are several possible reasons:
1. It may be due to the priority of CSS selectors. You can try using `!important` to increase the priority.
2. It may be that you have messed up the DOM structure, causing the CSS selector to not match the correct element.
3. It may be due to the development environment you are using that is causing the styles not to be compiled.

To troubleshoot the issue, and to help you understand the changes better, I would like you to fork the following example to reproduce the issue, and then provide a link that can reproduce the issue.
https://stackblitz.com/edit/react-3f6yhh?file=index.js

**Comment by Tian-YJ** [comment] 2024-05-12 12:07
1、Based on the problems I have raised, you are entirely free to reproduce them yourself and hopefully get an effective solution
2. The first two solutions you gave me have been tried before I asked, but they didn't work before I asked. Please check the screenshot of the third duplicate link you gave me. 
3. My demand is to change the background color of btn to black and select the background color of the date range to black. I hope to get an effective response. Thank you

![26451715515276_ pic](https://github.com/rsuite/rsuite/assets/35914704/822c695b-7dbc-47f2-b956-a4e0551e6c08)

**Comment by simonguo** [comment] 2024-05-13 02:09
https://rsuitejs.com/guide/css-variables/

**Comment by simonguo** [comment] 2024-05-13 02:12
> ![26451715515276_ pic](https://private-user-images.githubusercontent.com/35914704/329848019-822c695b-7dbc-47f2-b956-a4e0551e6c08.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NjYyNTAsIm5iZiI6MTcxNTU2NTk1MCwicGF0aCI6Ii8zNTkxNDcwNC8zMjk4NDgwMTktODIyYzY5NWItN2RiYy00N2YyLWI5NTYtYTRlMDU1MWU2YzA4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDAyMDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNDMzYjMwMTNhMzdhMzFmMzVhNTlhOGY2MjIyYTczMDgxMTNiZjhhMGY0MDNkNTIwNDBlOWE0Y2VjNjJiZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CMGLblS4Et7iXBOZtvOF6JrE4jDrvd7giTnrk_NEUSA)

Please share the link of this example publicly with me.

**Comment by Tian-YJ** [comment] 2024-05-13 02:54
I have solved
Take the style input the page body，not in the css file can solve


Thanks&nbsp;





------------------ Original ------------------
From: Simon Guo ***@***.***&gt;
Date: Mon,May 13,2024 10:12 AM
To: rsuite/rsuite ***@***.***&gt;
Cc: Tian-YJ ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [rsuite/rsuite] Invalid after style modification (Issue #3793)





  

  
Please share the link of this example publicly with me.

**Comment by simonguo** [comment] 2024-05-13 02:56
Okay, then I'll close the issue.

**Closed by simonguo** 2024-05-13 02:56 UTC
