### ISSUE TITLE
can't use Customize Theme with your Guid

### ISSUE THREAD

**Issue by Mahdibayat** [rsuite/rsuite#2470] opened 2022-04-25 09:52 UTC
hi, i flow your documentation Guide => use In React App
and then want to Customize Theme with less variable,
but not working i have error

![Capture](https://user-images.githubusercontent.com/24737348/165065495-c7f1b68b-ae43-438c-acf3-45401f5f2d29.PNG)

help me soon as possible please, thank you

**Comment by SevenOutman** [comment] 2022-04-25 20:44
Duplicate of #2436

**Closed** 2022-04-25 20:45 UTC
